#*****************************************************
#Input File Configurations
#*****************************************************

#Reference Sequence Information
refSampleName: "TAIR10" # Short ID for user to distinguish files
refAssembly: "../Arabidopsis_Data/TAIR10.1.all.fna" # Path to Reference Fenome fasta file
refSeqsFile: "../Arabidopsis_Data/RefSeqsToInclude.txt" # File of REF regions to include (one per line. Ex. Chromosomes only). Can be created with grep "><Chrom_Prefix>" <targetGenome> | tr -d ">"
refSize: 150000000 #Total size of the reference's sequences to be included
refChrmPrefix: "chr"
numRefContigs: 5 # Number of sequences/chromosomes present in assembly/genome (after selection for inclusion)

#Query Sequence Information
qrySampleName: "Ler" # Long ID for user to distinguish files
qryAssembly: "../Arabidopsis_Data/Ler.chr.all.v2.0.fasta" # Path to Query Assembly's fasta file
qrySeqsFile: "../Arabidopsis_Data/QrySeqsToInclude.txt" # File of regions to include (one per line. Ex: Chrosomes only). Can be created with grep "><CHROM_PREFIX>" <targetGenome> | tr -d ">"
qrySize: 150000000 #Total size of the query's sequences to be included
qryChrmPrefix: "chr"
numQryContigs: 5 # Number of sequences/chromosomes present in assembly/genome (after selection for inclusion)

#*****************************************************
# SV Pattern Evidence Configurations
#*****************************************************
svMinSize: 50 #Minimum size threshold (in bps) for an SV (EX: 50, based on min size commonly defined in literature)
svMaxSize: 300000 #Maximum size threshold (in bps) for an SV. Set based on max detectable size from tools with which you wish to compare  (EX: 300000)
vcfHeaderTemplate: ""#Path information for the file containing the desired VCF header based on the reference sample (Template provided in Repo's home directory)

#*****************************************************
# Environment and Working Directory Configurations
#*****************************************************

#Available Threads (Update to reflect hardware available)
threads: 30

#MUM&CO Configurations
mumCoScript: "$MUMCO/mumandco_v3.8.sh" # Path to MUM&Co.'s executable script (to be interpreted by shell)(Ex: "$MUMCO/mumandco_v3.8.sh")

#Designated Working Directory Information (Defaults can be built using 'build-workspace.sh' provided in home directory of repo)
genomesFolder: "Workflow_Outputs/Genomes"
alignResultsFolder: "Workflow_Outputs/Alignments"
svResultsFolder: "Workflow_Outputs/SV_Calls"
truvariResultsFolder: "Workflow_Outputs/Truvari_Results"
bedtoolsResultsFolder: "Workflow_Outputs/Bedtools_Results"
verifyAlignFolder: "Workflow_Outputs/VerifyAlign"

#Designated Conda Environment Information (Default YAML env file provided)(Note: Using only a single yaml file of all software reduces pipeline execution time)
condaEnvYAML: "All-Env.yaml" # Path to YAML file for conda env that majority/all of the dependencies are installed in"
syriCondaEnv: "All-Env.yaml" # Path to YAML file for conda env with SyRI dependencies installed

#*****************************************************
# Pipeline Software Configurations
#*****************************************************

#Nucmer Configurations (for more details see MUMmer4 manual) (MUMmer4 defaults for now)
minMatchLen: 20 # Minimum length threshold to consider an alignment (EX: 50)
minClusterSize: 65 # Minimum length threshold for exploring a cluster of matches (EX: 100)
maxEntend: 200 # Max distance nucmer will attempt to extend poor scoring regions before giving up (EX: 500)

#Delta-filter Configurations (for more details see MUMmer4 manual)
minIdentity: 0 # Minimum percent identity required to retain alignment (EX: 90)
minToFilter: 0 # Minimum length filtering threshold for alignments (EX: 100)

#Minimap2 Aligner Configurations (for more details see minimap2 --help)
presetForLR: "map-ont" # Predefined settings based on sequencing tech (Ex: map-ont, map-pb, map-hifi)
presetForAssemblies: "asm5" # Predefined settings for assembly to ref alignment based on similarity (asm5, asm10, asm20) (see minimap2 --help for similarity thresholds) 
minimapZDropForLR: "600,200" # Z drop score and Inversion Z drop score parameter in minimap (Default taken from cuteSV paper that compared similar tools)

#SAMTools Configurations (Default settings taken from SVIM-ASM paper)
memSettingForAssemblySort: "4G" # Requested/Required memory amount when sorting minimap2's assembly-to-ref alignment output

#General SV Caller Configurations (Default settings taken from CuteSV paper)
minMAPQForSVs: 20 # PHRED-scaled quality score (relates to probability of error and ranges from 4-60 w 10=10% error, 20=1%, 30=0.1%, 40=0.01%, 50=0.001%, 60=0.0001%)
minSuppReadsForSVs: 10 # Evidence threshold for the number of reads the support/indicate the presence of an SV
minSizeForSVs: 50 # Filtering for min size of the SV to be detected (50 based on common definition for SV min size in literature)
maxSizeForSVs: 300000 # Filtering maximum size for SV detectable by tools

#Alignment Verification Sample Configurations
verificationSampSize: 1000 # Total number of coord entries for each SV type to verify
indexInterval: 100000 #Index interval when indexing samtools depth output

#BEDTools Configurations
maxDistApart: 0 # Amount of separation allowed between entries that should still be merged (0 means they must be either overlapping or side-by-side) (EX:0)
overlapThreshold: 0.5 # (0.5 [or 50%] is a commonly use setting in several publications. Alternatively, svim-asm paper used 70%)

#BCFTools/Truvari Bench Configurations (see truvari help menu for more details)
overlapThreshold: 0.5 # (0.5 [or 50%] is a commonly use setting in several publications. Alternatively, svim-asm paper used 70%) 
maxRefDistance: 1000 # (Default setting chosen based on configuration used in svim-asm paper)

#*****************************************************
# Pipeline Benchmarking Configurations
#*****************************************************
#Path information for where to write benchmarking files
benchmarkDir: "Workflow_Outputs/Benchmarking"

#Frequency for how many times to repeat a task as part of benchmarking 
#(Note, increasing this parameter will significantly increase execution time. So unless benchmarking, recommended to be left at 1)
repeatsForBench: 1
